# permissions for end users to edit foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: foo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: new-pro
    app.kubernetes.io/part-of: new-pro
    app.kubernetes.io/managed-by: kustomize
  name: foo-editor-role
rules:
- apiGroups:
  - tutorial.my.domain
  resources:
  - foos
  - deployments.apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorial.my.domain
  resources:
  - foos/status
  verbs:
  - get
