# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: foo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: new-pro
    app.kubernetes.io/part-of: new-pro
    app.kubernetes.io/managed-by: kustomize
  name: foo-viewer-role
rules:
- apiGroups:
  - tutorial.my.domain
  resources:
  - foos
  - deployments.apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorial.my.domain
  resources:
  - foos/status
  verbs:
  - get
